### ISSUE TITLE
[Unban Request]

### ISSUE THREAD

**Issue by acse-bn20** [GraphicsProgramming/moderation-actions#1]
**Discord Username:** .__nyaki__
**Ban Reason:** -
**Ban Date:** -

**Why should your ban be lifted?**

Hi,

I joined the discord server on 13/5/2024 and I got kicked out on the same day even though I have done anything. I tried to join through discord invites I found online, but neither of them worked. Is there any way to join?

Best,
nyaki

**Comment by nickclark2016** [comment]
Unban request approved. You joined in the middle of a raid, and got hit with a ban wave trying to nuke all of the bot accounts. You should be good to rejoin via any existing invite link.

**Comment by acse-bn20** [comment]
Thank you. I could join now.
